#ifndef CLIENT_LOGGING_STRINGS_FR_H
#define CLIENT_LOGGING_STRINGS_FR_H

/* String constants for logging messages */
#define CLIENT_LOG_USAGE "Utilisation : %s <pseudo> [-s server_ip]\n"
#define CLIENT_LOG_USAGE_PSEUDO "  pseudo : Votre nom de joueur\n"
#define CLIENT_LOG_USAGE_SERVER "  -s <server_ip> : Optionnel - se connecter directement à l'IP du serveur au lieu de la découverte UDP\n"
#define CLIENT_LOG_USAGE_DISCOVERY "  Si aucune IP de serveur n'est fournie, le client utilisera la découverte par diffusion UDP.\n"
#define CLIENT_LOG_MISSING_PSEUDO "Il manque le pseudo. Usage: %s <pseudo> [-s server_ip]\n"
#define CLIENT_LOG_PLAYER_NAME "Joueur: %s\n"
#define CLIENT_LOG_WAITING_NOTIFICATION "En attente de notification\n"
#define CLIENT_LOG_INVALID_CHOICE "Choix invalide. Veuillez sélectionner 1-12.\n"
#define CLIENT_LOG_DISCONNECTING "Déconnexion...\n"
#define CLIENT_LOG_GOODBYE "Au revoir !\n\n"
#define CLIENT_LOG_BROADCAST_DISCOVERY "Diffusion de la demande de découverte sur le réseau local...\n"
#define CLIENT_LOG_NO_SERVER_FOUND "Aucun serveur trouvé sur le réseau local\n"
#define CLIENT_LOG_SERVER_DISCOVERED "Serveur découvert à %s:%d\n"
#define CLIENT_LOG_USING_PROVIDED_IP "Utilisation de l'IP du serveur fournie : %s\n"
#define CLIENT_LOG_CONNECTION_FAILED "Échec de connexion au serveur\n"
#define CLIENT_LOG_CONNECTED "Connecté au serveur à %s:%d\n"
#define CLIENT_LOG_INVALID_INPUT "Entree invalide\n"
#define CLIENT_LOG_SEND_CONNECT_FAILED "Échec d'envoi du message de connexion\n"
#define CLIENT_LOG_RECV_ACK_FAILED "Échec de réception de l'accusé de réception\n"
#define CLIENT_LOG_CONNECTION_REJECTED "Connexion rejetée : %s\n"
#define CLIENT_LOG_CONNECTION_SUCCESS "%s\n"

/* Basic commands logging constants */
#define CLIENT_LOG_LISTING_PLAYERS "\nListe des joueurs connectés...\n"
#define CLIENT_LOG_ERROR_SENDING_REQUEST "Erreur d'envoi de la requête : %s\n"
#define CLIENT_LOG_ERROR_RECEIVING_RESPONSE "Erreur de réception de la réponse\n"
#define CLIENT_LOG_CHALLENGE_PLAYER "\nDéfier un joueur\n"
#define CLIENT_LOG_ENTER_OPPONENT_PSEUDO "Entrez le pseudo de l'adversaire : "
#define CLIENT_LOG_PSEUDO_EMPTY "Le pseudo ne peut pas être vide\n"
#define CLIENT_LOG_CHALLENGE_SELF "Vous ne pouvez pas vous défier vous-même !\n"
#define CLIENT_LOG_ERROR_SENDING_CHALLENGE "Erreur d'envoi du défi : %s\n"
#define CLIENT_LOG_TIMEOUT_SERVER "Délai dépassé : Le serveur n'a pas répondu\n"
#define CLIENT_LOG_ERROR_RECEIVING_RESPONSE_WITH_ERR "Erreur de réception de la réponse : %s\n"
#define CLIENT_LOG_CANCELLED "Annulé.\n"
#define CLIENT_LOG_CHALLENGE_NOT_FOUND "Défi non trouvé\n"
#define CLIENT_LOG_NO_BIO_ENTERED "Aucune bio saisie\n"
#define CLIENT_LOG_ERROR_SENDING_BIO "Erreur d'envoi de la bio : %s\n"
#define CLIENT_LOG_VIEW_BIO_HEADER "\nVoir la bio du joueur\n"
#define CLIENT_LOG_VIEW_BIO_PROMPT "Entrez le nom du joueur : "
#define CLIENT_LOG_ERROR_READING_INPUT "Erreur de lecture de l'entrée\n"
#define CLIENT_LOG_NO_PLAYER_NAME_ENTERED "Aucun nom de joueur saisi\n"
#define CLIENT_LOG_VIEW_STATS_HEADER "\nVoir les statistiques du joueur\n"
#define CLIENT_LOG_VIEW_STATS_PROMPT "Entrez le nom du joueur (ou appuyez sur Entrée pour vos propres stats) : "
#define CLIENT_LOG_CHAT_MODE_HEADER "\nMode Chat Interactif\n"
#define CLIENT_LOG_CHAT_MODE_INSTRUCTIONS "Sélectionnez le destinataire : 'all' pour le chat global ou entrez un nom de joueur pour le chat privé\n"
#define CLIENT_LOG_CHAT_MODE_RECIPIENT "Destinataire : "
#define CLIENT_LOG_CHAT_MODE_GLOBAL "Mode chat global sélectionné. Tapez vos messages ci-dessous.\n"
#define CLIENT_LOG_CHAT_MODE_PRIVATE "Mode chat privé sélectionné. Envoi de messages à %s.\n"
#define CLIENT_LOG_CHAT_MODE_INSTRUCTIONS2 "Tapez votre message (ou 'exit'/'quit' pour quitter le mode chat) :\n"
#define CLIENT_LOG_CHAT_PROMPT "> "
#define CLIENT_LOG_CHAT_EXITED "Sorti du mode chat\n"
#define CLIENT_LOG_INVALID_RECIPIENT "Nom de destinataire invalide\n"
#define CLIENT_LOG_CHAT_MESSAGE_EMPTY "Le message ne peut pas être vide\n"
#define CLIENT_LOG_CHAT_ERROR_SENDING "Erreur d'envoi du message de chat : %s\n"

/* Play mode logging constants */
#define CLIENT_LOG_FAILED_SEND_BOARD_REQUEST "Échec d'envoi de la requête de plateau - connexion perdue\n"
#define CLIENT_LOG_NETWORK_SLOW "Réseau lent - délai de requête dépassé\n"
#define CLIENT_LOG_ERROR_SENDING_BOARD_REQUEST "Erreur d'envoi de la requête de plateau : %s\n"
#define CLIENT_LOG_SERVER_RESPONSE_TIMEOUT "Délai de réponse du serveur dépassé (tentative %d/%d) - nouvelle tentative...\n"
#define CLIENT_LOG_SERVER_NOT_RESPONDING "Le serveur ne répond pas après %d tentatives\n"
#define CLIENT_LOG_CONNECTION_LOST "Connexion perdue - veuillez redémarrer le client\n"
#define CLIENT_LOG_ERROR_RECEIVING_BOARD "Erreur de réception du plateau : %s\n"
#define CLIENT_LOG_UNEXPECTED_MESSAGE_TYPE "Type de message inattendu %d (attendu %d) - nouvelle tentative...\n"
#define CLIENT_LOG_PROTOCOL_ERROR "Erreur de protocole - type de message inattendu\n"
#define CLIENT_LOG_ENTER_PIT_OR_MENU "\nEntrez le numéro de fosse ou 'm' pour le menu : "
#define CLIENT_LOG_PROMPT "> "
#define CLIENT_LOG_RETURNING_TO_MENU "Retour au menu principal...\n"
#define CLIENT_LOG_NOT_YOUR_TURN "Ce n'est pas votre tour - en attente de l'adversaire\n"
#define CLIENT_LOG_INVALID_PIT "Fosse invalide ! Choisissez parmi %d-%d\n"
#define CLIENT_LOG_PIT_EMPTY "Cette fosse est vide !\n"
#define CLIENT_LOG_ERROR_SENDING_MOVE "Erreur d'envoi du mouvement : %s\n"
#define CLIENT_LOG_NO_ACTIVE_GAMES "Aucune partie active trouvée\n"
#define CLIENT_LOG_FAILED_SELECT_GAME "Échec de sélection de la partie\n"
#define CLIENT_LOG_ERROR_REQUESTING_INITIAL_BOARD "Erreur de requête du plateau initial : %s\n"
#define CLIENT_LOG_ERROR_REQUESTING_BOARD "Erreur de requête du plateau : %s\n"
#define CLIENT_LOG_CONNECTION_LOST_SHORT "Connexion perdue\n"
#define CLIENT_LOG_GAME_NO_LONGER_EXISTS "La partie n'existe plus\n"
#define CLIENT_LOG_MOVE_SENT "Mouvement envoyé...\n"
#define CLIENT_LOG_WAIT_FOR_MOVE_PROCESS "Veuillez attendre que le mouvement soit traité...\n"
#define CLIENT_LOG_LOADING_BOARD_STATE "Chargement de l'état du plateau...\n"
#define CLIENT_LOG_CHALLENGE_SENT_TO "Défi envoyé à %s !\n"
#define CLIENT_LOG_ENTERING_PLAY_MODE "\nENTRÉE EN MODE JEU\n"
#define CLIENT_LOG_USE_OPTION_2_FIRST "Utilisez l'option 2 pour défier un joueur d'abord !\n"
#define CLIENT_LOG_SELECTED_ACTIVE_GAME "Partie active sélectionnée :\n"
#define CLIENT_LOG_GAME_VS_FORMAT "   %s vs %s\n"
#define CLIENT_LOG_ACTIVE_GAMES_COUNT "\nVous avez %d parties actives :\n"
#define CLIENT_LOG_GAME_LIST_SEPARATOR "═══════════════════════════════════════════════════\n"
#define CLIENT_LOG_GAME_LIST_ITEM "  %d. %s vs %s\n"
#define CLIENT_LOG_SELECT_GAME_PROMPT "Sélectionnez la partie (1-%d) ou 0 pour annuler : "
#define CLIENT_LOG_PLAY_MODE_HEADER "\n═══════════════════════════════════════════════════\n"
#define CLIENT_LOG_PLAY_MODE_ACTIVE "    MODE JEU ACTIF (Piloté par Événements)\n"
#define CLIENT_LOG_PLAY_MODE_RETURN_HINT "    Appuyez sur 'm' + Entrée pour retourner au menu principal\n"
#define CLIENT_LOG_PLAY_MODE_FOOTER "═══════════════════════════════════════════════════\n\n"
#define CLIENT_LOG_GAME_OVER_HEADER "\n=== PARTIE TERMINÉE ===\n"
#define CLIENT_LOG_GAME_FINISHED "   PARTIE TERMINÉE !\n"
#define CLIENT_LOG_GAME_WINNER "   Gagnant : %s (Score : %d)\n"
#define CLIENT_LOG_GAME_PLAYER_A "   Joueur A : %s (Score : %d)\n"
#define CLIENT_LOG_GAME_PLAYER_B "   Joueur B : %s (Score : %d)\n"
#define CLIENT_LOG_GAME_DRAW "   Match nul ! (%d - %d)\n"
#define CLIENT_LOG_GAME_OVER_SEPARATOR "═══════════════════════════════════════════════════\n"
#define CLIENT_LOG_GAME_REMATCH_PROMPT "\nVoulez-vous les défier à nouveau ? (o/n) : "
#define CLIENT_LOG_MOVE_TIMEOUT "Délai de réponse du mouvement dépassé - actualisation du plateau\n"
#define CLIENT_LOG_UNEXPECTED_NOTIFICATION_TYPE "L'écouteur de notifications a reçu un type de message inattendu : %d\n"
#define CLIENT_LOG_BOARD_RECEIVED "État du plateau reçu avec succès\n"
#define CLIENT_LOG_GAME_REMOVED_ON_EXIT "Suppression de la partie %s des parties actives à la sortie\n"
#define CLIENT_LOG_GAME_LEFT_BUT_ACTIVE "Partie %s quittée mais gardée dans les parties actives (existe encore)\n"
#define CLIENT_LOG_EXITING_PLAY_MODE "\nSortie du mode jeu...\n"

/* Spectator mode logging constants */
#define CLIENT_LOG_SPECTATOR_MODE_HEADER "\n=== MODE SPECTATEUR ===\n"
#define CLIENT_LOG_SPECTATOR_MODE_TITLE "   MODE SPECTATEUR\n"
#define CLIENT_LOG_SPECTATOR_MODE_SEPARATOR "═══════════════════════════════════════════════════════\n\n"
#define CLIENT_LOG_FAILED_REQUEST_GAME_LIST "Échec de requête de la liste des parties\n"
#define CLIENT_LOG_TIMEOUT_GAME_LIST "Délai dépassé en attente de la liste des parties\n"
#define CLIENT_LOG_FAILED_RECEIVE_GAME_LIST "Échec de réception de la liste des parties\n"
#define CLIENT_LOG_NO_GAMES_IN_PROGRESS "Aucune partie en cours actuellement.\n"
#define CLIENT_LOG_PRESS_ENTER_CONTINUE "\nAppuyez sur Entrée pour continuer..."
#define CLIENT_LOG_AVAILABLE_GAMES "Parties disponibles à spectater :\n\n"
#define CLIENT_LOG_GAME_LIST_ITEM "  %d. %s vs %s\n"
#define CLIENT_LOG_GAME_ID "     ID de la partie : %s\n"
#define CLIENT_LOG_SPECTATORS "     Spectateurs : %d\n"
#define CLIENT_LOG_GAME_STATE "     État : "
#define CLIENT_LOG_GAME_STATE_WAITING "En attente\n"
#define CLIENT_LOG_GAME_STATE_IN_PROGRESS "En cours\n"
#define CLIENT_LOG_GAME_STATE_FINISHED "Terminée\n"
#define CLIENT_LOG_GAME_STATE_NEWLINE "\n"
#define CLIENT_LOG_SELECT_GAME "Sélectionnez la partie à spectater (1-%d, 0 pour annuler) : "
#define CLIENT_LOG_INVALID_GAME_SELECTION "Sélection de partie invalide\n"
#define CLIENT_LOG_SPECTATOR_ACK_MESSAGE "%s\n"
#define CLIENT_LOG_SPECTATOR_GAME_HEADER "\n=== PARTIE ===\n"
#define CLIENT_LOG_SPECTATOR_NOW_SPECTATING "   SPECTATE ACTUELLEMENT : %s vs %s\n"
#define CLIENT_LOG_SPECTATOR_SEPARATOR "═══════════════════════════════════════════════════════\n"
#define CLIENT_LOG_SPECTATOR_COMMANDS "\nCommandes :\n"
#define CLIENT_LOG_SPECTATOR_FAILED_SEND_REQUEST "Échec d'envoi de la requête de spectate\n"
#define CLIENT_LOG_SPECTATOR_TIMEOUT_ACK "Délai dépassé en attente de l'accusé de réception du spectate\n"
#define CLIENT_LOG_SPECTATOR_FAILED_RECEIVE_ACK "Échec de réception de l'accusé de réception du spectate\n"
#define CLIENT_LOG_SPECTATOR_REQUEST_DENIED "Requête de spectate refusée : %s\n"
#define CLIENT_LOG_SPECTATOR_COMMAND_REFRESH "  'r' - Actualiser le plateau\n"
#define CLIENT_LOG_SPECTATOR_COMMAND_QUIT "  'q' - Arrêter de spectater\n\n"
#define CLIENT_LOG_SPECTATOR_NEWLINE "\n"
#define CLIENT_LOG_SPECTATOR_SCORE_FORMAT "Score - %s : %d  |  %s : %d\n"
#define CLIENT_LOG_SPECTATOR_CURRENT_TURN "Tour actuel : %s\n"
#define CLIENT_LOG_SPECTATOR_PROMPT "Spectateur> "
#define CLIENT_LOG_SPECTATOR_FAILED_REFRESH "Échec d'actualisation du plateau\n"
#define CLIENT_LOG_SPECTATOR_BOARD_UPDATED "\nPlateau mis à jour ! Actualisation...\n"
#define CLIENT_LOG_SPECTATOR_STOPPED "\nArrêt du spectate.\n"
#define CLIENT_LOG_SPECTATOR_UNEXPECTED_MSG "Le mode spectateur a reçu un type de message inattendu : %d (attendu %d)\n"

/* UI display constants */
#define CLIENT_UI_BANNER_LINE1 "\n"
#define CLIENT_UI_BANNER_LINE2 "╔══════════════════════════════════════════════════════╗\n"
#define CLIENT_UI_BANNER_LINE3 "║            JEU AWALE - Client CLI                    ║\n"
#define CLIENT_UI_BANNER_LINE4 "╚══════════════════════════════════════════════════════╝\n"
#define CLIENT_UI_BANNER_LINE5 "\n"

#define CLIENT_UI_MENU_LINE1 "\n"
#define CLIENT_UI_MENU_LINE2 "═════════════════════════════════════════════════════════\n"
#define CLIENT_UI_MENU_LINE3 "                    MENU PRINCIPAL                       \n"
#define CLIENT_UI_MENU_LINE4 "═════════════════════════════════════════════════════════\n"
#define CLIENT_UI_MENU_OPTION1 "  1. Lister les joueurs connectés\n"
#define CLIENT_UI_MENU_OPTION2 "  2. Défier un joueur\n"
#define CLIENT_UI_MENU_OPTION3 "  3. Voir/Répondre aux défis"
#define CLIENT_UI_MENU_PENDING " [%d en attente]"
#define CLIENT_UI_MENU_LINE5 "\n"
#define CLIENT_UI_MENU_OPTION4 "  4. Définir votre bio\n"
#define CLIENT_UI_MENU_OPTION5 "  5. Voir la bio du joueur\n"
#define CLIENT_UI_MENU_OPTION6 "  6. Voir les statistiques du joueur\n"
#define CLIENT_UI_MENU_OPTION7 "  7. Mode jeu\n"
#define CLIENT_UI_MENU_OPTION8 "  8. Chat"
#define CLIENT_UI_MENU_ACTIVE " [%d partie%s active%s]"
#define CLIENT_UI_MENU_LINE6 "\n"
#define CLIENT_UI_MENU_OPTION9 "  9. Mode spectateur\n"
#define CLIENT_UI_MENU_OPTION10 "  10. Quitter\n"
#define CLIENT_UI_MENU_LINE7 "═════════════════════════════════════════════════════════\n"
#define CLIENT_UI_MENU_PROMPT "Votre choix : "

#define CLIENT_UI_BOARD_LINE1 "\n"
#define CLIENT_UI_BOARD_LINE2 "═══════════════════════════════════════════════════════════\n"
#define CLIENT_UI_BOARD_LINE3 "                    PLATEAU AWALE                          \n"
#define CLIENT_UI_BOARD_LINE4 "═══════════════════════════════════════════════════════════\n"
#define CLIENT_UI_BOARD_PLAYER_B "Joueur B: %s (Score: %d)                    %s\n"
#define CLIENT_UI_BOARD_LINE5 "\n"
#define CLIENT_UI_BOARD_TOP_ROW "   ┌────┬────┬────┬────┬────┬────┐\n"
#define CLIENT_UI_BOARD_TOP_PITS "   │%2d  │%2d  │%2d  │%2d  │%2d  │%2d  │\n"
#define CLIENT_UI_BOARD_TOP_LABELS "   │ 11 │ 10 │ 9  │ 8  │ 7  │ 6  │\n"
#define CLIENT_UI_BOARD_MIDDLE "   ├────┼────┼────┼────┼────┼────┤\n"
#define CLIENT_UI_BOARD_BOTTOM_LABELS "   │ 0  │ 1  │ 2  │ 3  │ 4  │ 5  │\n"
#define CLIENT_UI_BOARD_BOTTOM_PITS "   │%2d  │%2d  │%2d  │%2d  │%2d  │%2d  │\n"
#define CLIENT_UI_BOARD_BOTTOM_ROW "   └────┴────┴────┴────┴────┴────┘\n"
#define CLIENT_UI_BOARD_LINE6 "\n"
#define CLIENT_UI_BOARD_PLAYER_A "%s Joueur A: %s (Score: %d)\n"
#define CLIENT_UI_BOARD_LINE7 "═══════════════════════════════════════════════════════════\n"
#define CLIENT_UI_BOARD_GAME_OVER "PARTIE TERMINEE - "
#define CLIENT_UI_BOARD_WINNER_A "%s gagne!\n"
#define CLIENT_UI_BOARD_WINNER_B "%s gagne!\n"
#define CLIENT_UI_BOARD_DRAW "Match nul!\n"
#define CLIENT_UI_BOARD_CURRENT_TURN "Tour du joueur: %s\n"
#define CLIENT_UI_BOARD_PLAYER_A_HINT "%s peut jouer les fosses 0 à 5 (rangée du bas)\n"
#define CLIENT_UI_BOARD_PLAYER_B_HINT "%s peut jouer les fosses 6 à 11 (rangée du haut)\n"
#define CLIENT_UI_BOARD_LINE8 "═══════════════════════════════════════════════════════════\n"
#define CLIENT_UI_BOARD_LINE9 "\n"

#define CLIENT_UI_PLAYER_LIST_HEADER "\nJoueurs connectés (%d) :\n"
#define CLIENT_UI_PLAYER_LIST_SEPARATOR "─────────────────────────────\n"
#define CLIENT_UI_PLAYER_LIST_ITEM "  %d. %s (%s)\n"
#define CLIENT_UI_PLAYER_LIST_FOOTER "─────────────────────────────\n"

#define CLIENT_UI_CHALLENGE_SENT "Défi envoyé à %s !\n"
#define CLIENT_UI_CHALLENGE_SENT_INFO "Ils recevront une notification. Attendez qu'ils acceptent ou refusent.\n"
#define CLIENT_UI_CHALLENGE_ERROR "Erreur : %s\n"

#define CLIENT_UI_NO_CHALLENGES "\nAucun défi en attente\n"
#define CLIENT_UI_CHALLENGES_HEADER "\nDéfis en attente (%d) :\n"
#define CLIENT_UI_CHALLENGES_SEPARATOR "═══════════════════════════════════════════════════\n"
#define CLIENT_UI_CHALLENGE_ITEM "  %d. %s veut jouer !\n"
#define CLIENT_UI_CHALLENGES_FOOTER "═══════════════════════════════════════════════════\n"
#define CLIENT_UI_CHALLENGES_OPTIONS "\nChoisissez une option :\n"
#define CLIENT_UI_CHALLENGES_ACCEPT "  [numéro] Accepter le défi\n"
#define CLIENT_UI_CHALLENGES_DECLINE "  d[numéro] Refuser le défi\n"
#define CLIENT_UI_CHALLENGES_CANCEL "  0 Annuler\n"
#define CLIENT_UI_CHALLENGES_PROMPT "Votre choix : "

#define CLIENT_UI_CHALLENGE_ACCEPTED "Défi de %s accepté ! La partie commencera bientôt...\n"
#define CLIENT_UI_CHALLENGE_DECLINED "Défi de %s refusé\n"

#define CLIENT_UI_BIO_PROMPT_HEADER "\nDéfinition de votre bio (max 10 lignes, 255 caractères chacune)\n"
#define CLIENT_UI_BIO_PROMPT_INSTRUCTIONS "Entrez les lignes de votre bio. Entrez une ligne vide pour terminer :\n"
#define CLIENT_UI_BIO_PROMPT_LINE "Ligne %d : "
#define CLIENT_UI_BIO_UPDATED "Bio mise à jour avec succès (%d lignes)\n"

#define CLIENT_UI_BIO_DISPLAY_HEADER "\nBio de %s :\n"
#define CLIENT_UI_BIO_DISPLAY_SEPARATOR "─────────────────────────────\n"
#define CLIENT_UI_BIO_DISPLAY_EMPTY "  (Aucune bio définie)\n"
#define CLIENT_UI_BIO_DISPLAY_LINE "  %s\n"
#define CLIENT_UI_BIO_DISPLAY_FOOTER "─────────────────────────────\n"
#define CLIENT_UI_BIO_DISPLAY_ERROR "%s\n"

#define CLIENT_UI_STATS_HEADER "\nStatistiques de %s :\n"
#define CLIENT_UI_STATS_SEPARATOR "─────────────────────────────\n"
#define CLIENT_UI_STATS_GAMES_PLAYED "  Parties jouées : %d\n"
#define CLIENT_UI_STATS_GAMES_WON "  Parties gagnées : %d\n"
#define CLIENT_UI_STATS_GAMES_LOST "  Parties perdues : %d\n"
#define CLIENT_UI_STATS_TOTAL_SCORE "  Score total : %d\n"
#define CLIENT_UI_STATS_WIN_RATE "  Taux de victoire : %.1f%%\n"
#define CLIENT_UI_STATS_FIRST_SEEN "  Première vue : %s"
#define CLIENT_UI_STATS_LAST_SEEN "  Dernière vue : %s"
#define CLIENT_UI_STATS_FOOTER "─────────────────────────────\n"
#define CLIENT_UI_STATS_DISPLAY_ERROR "%s\n"

#define CLIENT_UI_CHAT_MODE_HEADER "\nMode Chat Interactif\n"
#define CLIENT_UI_CHAT_MODE_INSTRUCTIONS "Sélectionnez le destinataire : 'all' pour le chat global ou entrez un nom de joueur pour le chat privé\n"
#define CLIENT_UI_CHAT_MODE_RECIPIENT "Destinataire : "
#define CLIENT_UI_CHAT_MODE_GLOBAL "Mode chat global sélectionné. Tapez vos messages ci-dessous.\n"
#define CLIENT_UI_CHAT_MODE_PRIVATE "Mode chat privé sélectionné. Envoi de messages à %s.\n"
#define CLIENT_UI_CHAT_ERROR "Erreur : %s\n"

#define CLIENT_UI_NOTIFICATION_HEADER "\n\n=== NOTIFICATIONS ===\n"
#define CLIENT_UI_NOTIFICATION_CHALLENGE "   DÉFI REÇU !\n"
#define CLIENT_UI_NOTIFICATION_MESSAGE "   %s\n"
#define CLIENT_UI_NOTIFICATION_CHALLENGE_HINT "   Utilisez l'option 3 pour accepter ou refuser ce défi\n"
#define CLIENT_UI_NOTIFICATION_SEPARATOR "═══════════════════════════════════════════════════\n"
#define CLIENT_UI_NOTIFICATION_PROMPT "Votre choix : "

#define CLIENT_UI_GAME_STARTED_HEADER "\n\n=== PARTIE ===\n"
#define CLIENT_UI_GAME_STARTED_TITLE "   PARTIE COMMENCÉE !\n"
#define CLIENT_UI_GAME_STARTED_ID "   ID de la partie : %s\n"
#define CLIENT_UI_GAME_STARTED_PLAYERS "   Joueurs : %s vs %s\n"
#define CLIENT_UI_GAME_STARTED_YOUR_SIDE "   Vous êtes : %s\n"
#define CLIENT_UI_GAME_STARTED_HINT "   Utilisez l'option 7 pour entrer en mode jeu\n"
#define CLIENT_UI_GAME_STARTED_SEPARATOR "═══════════════════════════════════════════════════\n"
#define CLIENT_UI_GAME_STARTED_PROMPT "Votre choix : "

#define CLIENT_UI_SPECTATOR_JOINED_HEADER "\n\n=== SPECTATEUR ===\n"
#define CLIENT_UI_SPECTATOR_JOINED_TITLE "   SPECTATEUR REJOINT : %s\n"
#define CLIENT_UI_SPECTATOR_JOINED_ID "   ID de la partie : %s\n"
#define CLIENT_UI_SPECTATOR_JOINED_COUNT "   Total des spectateurs : %d\n"
#define CLIENT_UI_SPECTATOR_JOINED_SEPARATOR "═══════════════════════════════════════════════════\n"
#define CLIENT_UI_SPECTATOR_JOINED_PROMPT "Votre choix : "

#define CLIENT_UI_GAME_OVER_HEADER "\n\n=== PARTIE TERMINÉE ===\n"
#define CLIENT_UI_GAME_OVER_TITLE "   PARTIE TERMINÉE !\n"
#define CLIENT_UI_GAME_OVER_MESSAGE "   %s\n"
#define CLIENT_UI_GAME_OVER_SEPARATOR "═══════════════════════════════════════════════════\n"
#define CLIENT_UI_GAME_OVER_PROMPT "Votre choix : "

#define CLIENT_UI_CHAT_MESSAGE_HEADER "\n\n=== CHAT ===\n"
#define CLIENT_UI_CHAT_MESSAGE_GLOBAL "   CHAT GLOBAL de %s :\n"
#define CLIENT_UI_CHAT_MESSAGE_PRIVATE "   MESSAGE PRIVÉ de %s :\n"
#define CLIENT_UI_CHAT_MESSAGE_TEXT "   %s\n"
#define CLIENT_UI_CHAT_MESSAGE_SEPARATOR "═══════════════════════════════════════════════════\n"
#define CLIENT_UI_CHAT_MESSAGE_PROMPT "Votre choix : "

#define CLIENT_UI_CONNECTION_LOST "\nConnexion perdue - serveur déconnecté\n"
#define CLIENT_UI_NETWORK_ERROR "\nErreur réseau : %s (tentative %d/%d)\n"
#define CLIENT_UI_NETWORK_ERROR_MAX "Trop d'erreurs consécutives - déconnexion\n"

#define CLIENT_UI_TURN_YOUR_TURN "\nVOTRE TOUR !\n"
#define CLIENT_UI_TURN_LEGAL_MOVES "   Mouvements légaux : "
#define CLIENT_UI_TURN_MOVE_SEPARATOR "%d "
#define CLIENT_UI_TURN_NO_MOVES "(aucun)"
#define CLIENT_UI_TURN_LINE1 "\n"
#define CLIENT_UI_TURN_PROMPT "\nEntrez le numéro de fosse ou 'm' pour le menu : "

#define CLIENT_UI_WAITING_OPPONENT "\nEn attente de l'adversaire...\n"
#define CLIENT_UI_WAITING_HINT "   Tapez 'm' + Entrée pour retourner au menu principal\n"
#define CLIENT_UI_WAITING_PROMPT "> "

#define CLIENT_UI_PLAY_ERROR "%s\n"

#define CLIENT_UI_BOARD_SIMPLE_LINE1 "\n"
#define CLIENT_UI_BOARD_SIMPLE_PLAYER_B "  [%2d][%2d][%2d][%2d][%2d][%2d]  <- Joueur B (Score : %d)\n"
#define CLIENT_UI_BOARD_SIMPLE_PLAYER_A "  [%2d][%2d][%2d][%2d][%2d][%2d]  <- Joueur A (Score : %d)\n"
#define CLIENT_UI_BOARD_SIMPLE_TURN "  Tour actuel : Joueur %c\n"
#define CLIENT_UI_BOARD_SIMPLE_LINE2 "\n"

#define CLIENT_UI_BOARD_DETAILED_LINE1 "\n"
#define CLIENT_UI_BOARD_DETAILED_LINE2 "═══════════════════════════════════════════════════════════\n"
#define CLIENT_UI_BOARD_DETAILED_LINE3 "                    PLATEAU AWALE                          \n"
#define CLIENT_UI_BOARD_DETAILED_LINE4 "═══════════════════════════════════════════════════════════\n"
#define CLIENT_UI_BOARD_DETAILED_PLAYER_B "Joueur B: %s (Score: %d)                    %s\n"
#define CLIENT_UI_BOARD_DETAILED_LINE5 "\n"
#define CLIENT_UI_BOARD_DETAILED_TOP_ROW "   ┌────┬────┬────┬────┬────┬────┐\n"
#define CLIENT_UI_BOARD_DETAILED_TOP_PITS "   │%2d  │%2d  │%2d  │%2d  │%2d  │%2d  │\n"
#define CLIENT_UI_BOARD_DETAILED_TOP_LABELS "   │ 11 │ 10 │ 9  │ 8  │ 7  │ 6  │\n"
#define CLIENT_UI_BOARD_DETAILED_MIDDLE "   ├────┼────┼────┼────┼────┼────┤\n"
#define CLIENT_UI_BOARD_DETAILED_BOTTOM_LABELS "   │ 0  │ 1  │ 2  │ 3  │ 4  │ 5  │\n"
#define CLIENT_UI_BOARD_DETAILED_BOTTOM_PITS "   │%2d  │%2d  │%2d  │%2d  │%2d  │%2d  │\n"
#define CLIENT_UI_BOARD_DETAILED_BOTTOM_ROW "   └────┴────┴────┴────┴────┘\n"
#define CLIENT_UI_BOARD_DETAILED_LINE6 "\n"
#define CLIENT_UI_BOARD_DETAILED_PLAYER_A "%s Joueur A: %s (Score: %d)\n"
#define CLIENT_UI_BOARD_DETAILED_LINE7 "═══════════════════════════════════════════════════════════\n"
#define CLIENT_UI_BOARD_DETAILED_GAME_OVER "PARTIE TERMINEE - "
#define CLIENT_UI_BOARD_DETAILED_WINNER_A "%s gagne!\n"
#define CLIENT_UI_BOARD_DETAILED_WINNER_B "%s gagne!\n"
#define CLIENT_UI_BOARD_DETAILED_DRAW "Match nul!\n"
#define CLIENT_UI_BOARD_DETAILED_CURRENT_TURN "Tour du joueur: %s\n"
#define CLIENT_UI_BOARD_DETAILED_LINE8 "═══════════════════════════════════════════════════════════\n"
#define CLIENT_UI_BOARD_DETAILED_LINE9 "\n"

#endif /* CLIENT_LOGGING_STRINGS_FR_H */