#ifndef CLIENT_LOGGING_STRINGS_H
#define CLIENT_LOGGING_STRINGS_H

/* String constants for logging messages */
#define CLIENT_LOG_USAGE "Usage: %s <pseudo> [-s server_ip]\n"
#define CLIENT_LOG_USAGE_PSEUDO "  pseudo: Your player name\n"
#define CLIENT_LOG_USAGE_SERVER "  -s <server_ip> : Optional - directly connect to server IP instead of UDP discovery\n"
#define CLIENT_LOG_USAGE_DISCOVERY "  If no server IP is provided the client will use UDP broadcast discovery.\n"
#define CLIENT_LOG_MISSING_PSEUDO "Il manque le pseudo. Usage: %s <pseudo> [-s server_ip]\n"
#define CLIENT_LOG_PLAYER_NAME "Joueur: %s\n"
#define CLIENT_LOG_WAITING_NOTIFICATION "En attente de notification\n"
#define CLIENT_LOG_INVALID_CHOICE "Invalid choice. Please select 1-13.\n"
#define CLIENT_LOG_DISCONNECTING "Disconnecting...\n"
#define CLIENT_LOG_GOODBYE "Goodbye!\n\n"
#define CLIENT_LOG_BROADCAST_DISCOVERY "Broadcasting discovery request on local network...\n"
#define CLIENT_LOG_NO_SERVER_FOUND "No server found on local network\n"
#define CLIENT_LOG_SERVER_DISCOVERED "Server discovered at %s:%d\n"
#define CLIENT_LOG_USING_PROVIDED_IP "Using provided server IP: %s\n"
#define CLIENT_LOG_CONNECTION_FAILED "Failed to connect to server\n"
#define CLIENT_LOG_CONNECTED "Connected to server at %s:%d\n"
#define CLIENT_LOG_INVALID_INPUT "Entree invalide\n"
#define CLIENT_LOG_SEND_CONNECT_FAILED "Failed to send connect message\n"
#define CLIENT_LOG_RECV_ACK_FAILED "Failed to receive acknowledgment\n"
#define CLIENT_LOG_CONNECTION_REJECTED "Connection rejected: %s\n"
#define CLIENT_LOG_CONNECTION_SUCCESS "%s\n"

/* Basic commands logging constants */
#define CLIENT_LOG_LISTING_PLAYERS "\nListing connected players...\n"
#define CLIENT_LOG_ERROR_SENDING_REQUEST "Error sending request: %s\n"
#define CLIENT_LOG_ERROR_RECEIVING_RESPONSE "Error receiving response\n"
#define CLIENT_LOG_CHALLENGE_PLAYER "\nChallenge a player\n"
#define CLIENT_LOG_ENTER_OPPONENT_PSEUDO "Enter opponent's pseudo: "
#define CLIENT_LOG_PSEUDO_EMPTY "Pseudo cannot be empty\n"
#define CLIENT_LOG_CHALLENGE_SELF "You cannot challenge yourself!\n"
#define CLIENT_LOG_ERROR_SENDING_CHALLENGE "Error sending challenge: %s\n"
#define CLIENT_LOG_TIMEOUT_SERVER "Timeout: Server did not respond\n"
#define CLIENT_LOG_ERROR_RECEIVING_RESPONSE_WITH_ERR "Error receiving response: %s\n"
#define CLIENT_LOG_CANCELLED "Cancelled.\n"
#define CLIENT_LOG_CHALLENGE_NOT_FOUND "Challenge not found\n"
#define CLIENT_LOG_NO_BIO_ENTERED "No bio entered\n"
#define CLIENT_LOG_ERROR_SENDING_BIO "Error sending bio: %s\n"
#define CLIENT_LOG_VIEW_BIO_HEADER "\nView player bio\n"
#define CLIENT_LOG_VIEW_BIO_PROMPT "Enter player name: "
#define CLIENT_LOG_ERROR_READING_INPUT "Error reading input\n"
#define CLIENT_LOG_NO_PLAYER_NAME_ENTERED "No player name entered\n"
#define CLIENT_LOG_VIEW_STATS_HEADER "\nView player statistics\n"
#define CLIENT_LOG_VIEW_STATS_PROMPT "Enter player name (or press Enter for your own stats): "
#define CLIENT_LOG_CHAT_MODE_HEADER "\nInteractive Chat Mode\n"
#define CLIENT_LOG_CHAT_MODE_INSTRUCTIONS "Select recipient: 'all' for global chat or enter a player name for private chat\n"
#define CLIENT_LOG_CHAT_MODE_RECIPIENT "Recipient: "
#define CLIENT_LOG_CHAT_MODE_GLOBAL "Global chat mode selected. Type your messages below.\n"
#define CLIENT_LOG_CHAT_MODE_PRIVATE "Private chat mode selected. Sending messages to %s.\n"
#define CLIENT_LOG_CHAT_MODE_INSTRUCTIONS2 "Type your message (or 'exit'/'quit' to leave chat mode):\n"
#define CLIENT_LOG_CHAT_PROMPT "> "
#define CLIENT_LOG_CHAT_EXITED "Exited chat mode\n"
#define CLIENT_LOG_INVALID_RECIPIENT "Invalid recipient name\n"
#define CLIENT_LOG_CHAT_MESSAGE_EMPTY "Message cannot be empty\n"
#define CLIENT_LOG_CHAT_ERROR_SENDING "Error sending chat message: %s\n"

/* Play mode logging constants */
#define CLIENT_LOG_FAILED_SEND_BOARD_REQUEST "Failed to send board request - connection lost\n"
#define CLIENT_LOG_NETWORK_SLOW "Network slow - request timeout\n"
#define CLIENT_LOG_ERROR_SENDING_BOARD_REQUEST "Error sending board request: %s\n"
#define CLIENT_LOG_SERVER_RESPONSE_TIMEOUT "Server response timeout (attempt %d/%d) - retrying...\n"
#define CLIENT_LOG_SERVER_NOT_RESPONDING "Server not responding after %d attempts\n"
#define CLIENT_LOG_CONNECTION_LOST "Connection lost - please restart client\n"
#define CLIENT_LOG_ERROR_RECEIVING_BOARD "Error receiving board: %s\n"
#define CLIENT_LOG_UNEXPECTED_MESSAGE_TYPE "Unexpected message type %d (expected %d) - retrying...\n"
#define CLIENT_LOG_PROTOCOL_ERROR "Protocol error - unexpected message type\n"
#define CLIENT_LOG_ENTER_PIT_OR_MENU "\nEnter pit number or 'm' for menu: "
#define CLIENT_LOG_PROMPT "> "
#define CLIENT_LOG_RETURNING_TO_MENU "Returning to main menu...\n"
#define CLIENT_LOG_NOT_YOUR_TURN "Not your turn - waiting for opponent\n"
#define CLIENT_LOG_INVALID_PIT "Invalid pit! Choose from %d-%d\n"
#define CLIENT_LOG_PIT_EMPTY "That pit is empty!\n"
#define CLIENT_LOG_ERROR_SENDING_MOVE "Error sending move: %s\n"
#define CLIENT_LOG_NO_ACTIVE_GAMES "No active games found\n"
#define CLIENT_LOG_FAILED_SELECT_GAME "Failed to select game\n"
#define CLIENT_LOG_ERROR_REQUESTING_INITIAL_BOARD "Error requesting initial board: %s\n"
#define CLIENT_LOG_ERROR_REQUESTING_BOARD "Error requesting board: %s\n"
#define CLIENT_LOG_CONNECTION_LOST_SHORT "Connection lost\n"
#define CLIENT_LOG_GAME_NO_LONGER_EXISTS "Game no longer exists\n"
#define CLIENT_LOG_MOVE_SENT "Move sent...\n"
#define CLIENT_LOG_WAIT_FOR_MOVE_PROCESS "Please wait for move to be processed...\n"
#define CLIENT_LOG_LOADING_BOARD_STATE "Loading board state...\n"
#define CLIENT_LOG_CHALLENGE_SENT_TO "Challenge sent to %s!\n"
#define CLIENT_LOG_ENTERING_PLAY_MODE "\nENTERING PLAY MODE\n"
#define CLIENT_LOG_USE_OPTION_2_FIRST "Use option 2 to challenge a player first!\n"
#define CLIENT_LOG_SELECTED_ACTIVE_GAME "Selected your active game:\n"
#define CLIENT_LOG_GAME_VS_FORMAT "   %s vs %s\n"
#define CLIENT_LOG_ACTIVE_GAMES_COUNT "\nYou have %d active games:\n"
#define CLIENT_LOG_GAME_LIST_SEPARATOR "═══════════════════════════════════════════════════\n"
#define CLIENT_LOG_GAME_LIST_ITEM "  %d. %s vs %s\n"
#define CLIENT_LOG_SELECT_GAME_PROMPT "Select game (1-%d) or 0 to cancel: "
#define CLIENT_LOG_PLAY_MODE_HEADER "\n═══════════════════════════════════════════════════\n"
#define CLIENT_LOG_PLAY_MODE_ACTIVE "    PLAY MODE ACTIVE (Event-Driven)\n"
#define CLIENT_LOG_PLAY_MODE_RETURN_HINT "    Press 'm' + Enter to return to main menu\n"
#define CLIENT_LOG_PLAY_MODE_FOOTER "═══════════════════════════════════════════════════\n\n"
#define CLIENT_LOG_GAME_OVER_HEADER "\n=== GAME OVER ===\n"
#define CLIENT_LOG_GAME_FINISHED "   GAME FINISHED!\n"
#define CLIENT_LOG_GAME_WINNER "   Winner: %s (Score: %d)\n"
#define CLIENT_LOG_GAME_PLAYER_A "   Player A: %s (Score: %d)\n"
#define CLIENT_LOG_GAME_PLAYER_B "   Player B: %s (Score: %d)\n"
#define CLIENT_LOG_GAME_DRAW "   Draw! (%d - %d)\n"
#define CLIENT_LOG_GAME_OVER_SEPARATOR "═══════════════════════════════════════════════════\n"
#define CLIENT_LOG_GAME_REMATCH_PROMPT "\nWould you like to challenge them again? (y/n): "
#define CLIENT_LOG_MOVE_TIMEOUT "Move response timeout - refreshing board\n"
#define CLIENT_LOG_UNEXPECTED_NOTIFICATION_TYPE "Notification listener received unexpected message type: %d\n"
#define CLIENT_LOG_BOARD_RECEIVED "Board state received successfully\n"
#define CLIENT_LOG_GAME_REMOVED_ON_EXIT "Removing game %s from active games on exit\n"
#define CLIENT_LOG_GAME_LEFT_BUT_ACTIVE "Left game %s but keeping in active games (still exists)\n"
#define CLIENT_LOG_EXITING_PLAY_MODE "\nExiting play mode...\n"

/* Spectator mode logging constants */
#define CLIENT_LOG_SPECTATOR_MODE_HEADER "\n=== PRIVATE SPECTATOR MODE ===\n"
#define CLIENT_LOG_SPECTATOR_MODE_TITLE "   PRIVATE SPECTATOR MODE\n"
#define CLIENT_LOG_SPECTATOR_MODE_SEPARATOR "═══════════════════════════════════════════════════════\n\n"
#define CLIENT_LOG_SPECTATOR_MODE_INFO "   Note: You can only spectate games where you are friends with at least one player.\n\n"
#define CLIENT_LOG_FAILED_REQUEST_GAME_LIST "Failed to request game list\n"
#define CLIENT_LOG_TIMEOUT_GAME_LIST "Timeout waiting for game list\n"
#define CLIENT_LOG_FAILED_RECEIVE_GAME_LIST "Failed to receive game list\n"
#define CLIENT_LOG_NO_GAMES_IN_PROGRESS "No games currently in progress.\n"
#define CLIENT_LOG_PRESS_ENTER_CONTINUE "\nPress Enter to continue..."
#define CLIENT_LOG_AVAILABLE_GAMES "Available games to spectate:\n\n"
#define CLIENT_LOG_GAME_LIST_ITEM "  %d. %s vs %s\n"
#define CLIENT_LOG_GAME_ID "     Game ID: %s\n"
#define CLIENT_LOG_SPECTATORS "     Spectators: %d\n"
#define CLIENT_LOG_GAME_STATE "     State: "
#define CLIENT_LOG_GAME_STATE_WAITING "Waiting\n"
#define CLIENT_LOG_GAME_STATE_IN_PROGRESS "In Progress\n"
#define CLIENT_LOG_GAME_STATE_FINISHED "Finished\n"
#define CLIENT_LOG_GAME_STATE_NEWLINE "\n"
#define CLIENT_LOG_SELECT_GAME "Select game to spectate (1-%d, 0 to cancel): "
#define CLIENT_LOG_INVALID_GAME_SELECTION "Invalid game selection\n"
#define CLIENT_LOG_SPECTATOR_ACK_MESSAGE "%s\n"
#define CLIENT_LOG_SPECTATOR_GAME_HEADER "\n=== GAME ===\n"
#define CLIENT_LOG_SPECTATOR_NOW_SPECTATING "   NOW SPECTATING: %s vs %s\n"
#define CLIENT_LOG_SPECTATOR_SEPARATOR "═══════════════════════════════════════════════════════\n"
#define CLIENT_LOG_SPECTATOR_COMMANDS "\nCommands:\n"
#define CLIENT_LOG_SPECTATOR_FAILED_SEND_REQUEST "Failed to send spectate request\n"
#define CLIENT_LOG_SPECTATOR_TIMEOUT_ACK "Timeout waiting for spectate acknowledgment\n"
#define CLIENT_LOG_SPECTATOR_FAILED_RECEIVE_ACK "Failed to receive spectate acknowledgment\n"
#define CLIENT_LOG_SPECTATOR_REQUEST_DENIED "Spectate request denied: %s\n"
#define CLIENT_LOG_SPECTATOR_COMMAND_REFRESH "  'r' - Refresh board\n"
#define CLIENT_LOG_SPECTATOR_COMMAND_QUIT "  'q' - Stop spectating\n\n"
#define CLIENT_LOG_SPECTATOR_NEWLINE "\n"
#define CLIENT_LOG_SPECTATOR_SCORE_FORMAT "Score - %s: %d  |  %s: %d\n"
#define CLIENT_LOG_SPECTATOR_CURRENT_TURN "Current turn: %s\n"
#define CLIENT_LOG_SPECTATOR_PROMPT "Spectator> "
#define CLIENT_LOG_SPECTATOR_FAILED_REFRESH "Failed to refresh board\n"
#define CLIENT_LOG_SPECTATOR_BOARD_UPDATED "\nBoard updated! Refreshing...\n"
#define CLIENT_LOG_SPECTATOR_STOPPED "\nStopped spectating.\n"
#define CLIENT_LOG_SPECTATOR_UNEXPECTED_MSG "Spectator mode received unexpected message type: %d (expected %d)\n"

/* UI display constants */
#define CLIENT_UI_BANNER_LINE1 "\n"
#define CLIENT_UI_BANNER_LINE2 "╔══════════════════════════════════════════════════════╗\n"
#define CLIENT_UI_BANNER_LINE3 "║            AWALE GAME - CLI Client                   ║\n"
#define CLIENT_UI_BANNER_LINE4 "╚══════════════════════════════════════════════════════╝\n"
#define CLIENT_UI_BANNER_LINE5 "\n"

#define CLIENT_UI_MENU_LINE1 "\n"
#define CLIENT_UI_MENU_LINE2 "═════════════════════════════════════════════════════════\n"
#define CLIENT_UI_MENU_LINE3 "                    MAIN MENU                            \n"
#define CLIENT_UI_MENU_LINE4 "═════════════════════════════════════════════════════════\n"
#define CLIENT_UI_MENU_OPTION1 "  1. List connected players\n"
#define CLIENT_UI_MENU_OPTION2 "  2. Challenge a player\n"
#define CLIENT_UI_MENU_OPTION3 "  3. View/Respond to challenges"
#define CLIENT_UI_MENU_PENDING " [%d pending]"
#define CLIENT_UI_MENU_LINE5 "\n"
#define CLIENT_UI_MENU_OPTION4 "  4. Set your bio\n"
#define CLIENT_UI_MENU_OPTION5 "  5. View player bio\n"
#define CLIENT_UI_MENU_OPTION6 "  6. View player statistics\n"
#define CLIENT_UI_MENU_OPTION7 "  7. Play mode\n"
#define CLIENT_UI_MENU_OPTION8 "  8. Chat"
#define CLIENT_UI_MENU_ACTIVE " [%d active game%s]"
#define CLIENT_UI_MENU_LINE6 "\n"
#define CLIENT_UI_MENU_OPTION9 "  9. Spectator mode\n"
#define CLIENT_UI_MENU_OPTION10 "  10. Friend management\n"
#define CLIENT_UI_MENU_OPTION11 "  11. List saved games\n"
#define CLIENT_UI_MENU_OPTION12 "  12. View saved game\n"
#define CLIENT_UI_MENU_OPTION13 "  13. Quit\n"
#define CLIENT_UI_MENU_LINE7 "═════════════════════════════════════════════════════════\n"
#define CLIENT_UI_MENU_PROMPT "Your choice: "

#define CLIENT_UI_BOARD_LINE1 "\n"
#define CLIENT_UI_BOARD_LINE2 "═══════════════════════════════════════════════════════════\n"
#define CLIENT_UI_BOARD_LINE3 "                    PLATEAU AWALE                          \n"
#define CLIENT_UI_BOARD_LINE4 "═══════════════════════════════════════════════════════════\n"
#define CLIENT_UI_BOARD_PLAYER_B "Joueur B: %s (Score: %d)                    %s\n"
#define CLIENT_UI_BOARD_LINE5 "\n"
#define CLIENT_UI_BOARD_TOP_ROW "   ┌────┬────┬────┬────┬────┬────┐\n"
#define CLIENT_UI_BOARD_TOP_PITS "   │%2d  │%2d  │%2d  │%2d  │%2d  │%2d  │\n"
#define CLIENT_UI_BOARD_TOP_LABELS "   │ 11 │ 10 │ 9  │ 8  │ 7  │ 6  │\n"
#define CLIENT_UI_BOARD_MIDDLE "   ├────┼────┼────┼────┼────┼────┤\n"
#define CLIENT_UI_BOARD_BOTTOM_LABELS "   │ 0  │ 1  │ 2  │ 3  │ 4  │ 5  │\n"
#define CLIENT_UI_BOARD_BOTTOM_PITS "   │%2d  │%2d  │%2d  │%2d  │%2d  │%2d  │\n"
#define CLIENT_UI_BOARD_BOTTOM_ROW "   └────┴────┴────┴────┴────┴────┘\n"
#define CLIENT_UI_BOARD_LINE6 "\n"
#define CLIENT_UI_BOARD_PLAYER_A "%s Joueur A: %s (Score: %d)\n"
#define CLIENT_UI_BOARD_LINE7 "═══════════════════════════════════════════════════════════\n"
#define CLIENT_UI_BOARD_GAME_OVER "PARTIE TERMINEE - "
#define CLIENT_UI_BOARD_WINNER_A "%s gagne!\n"
#define CLIENT_UI_BOARD_WINNER_B "%s gagne!\n"
#define CLIENT_UI_BOARD_DRAW "Match nul!\n"
#define CLIENT_UI_BOARD_CURRENT_TURN "Tour du joueur: %s\n"
#define CLIENT_UI_BOARD_PLAYER_A_HINT "%s peut jouer les fosses 0 à 5 (rangée du bas)\n"
#define CLIENT_UI_BOARD_PLAYER_B_HINT "%s peut jouer les fosses 6 à 11 (rangée du haut)\n"
#define CLIENT_UI_BOARD_LINE8 "═══════════════════════════════════════════════════════════\n"
#define CLIENT_UI_BOARD_LINE9 "\n"

#define CLIENT_UI_PLAYER_LIST_HEADER "\nConnected players (%d):\n"
#define CLIENT_UI_PLAYER_LIST_SEPARATOR "─────────────────────────────\n"
#define CLIENT_UI_PLAYER_LIST_ITEM "  %d. %s\n"
#define CLIENT_UI_PLAYER_LIST_FOOTER "─────────────────────────────\n"

#define CLIENT_UI_CHALLENGE_SENT "Challenge sent to %s!\n"
#define CLIENT_UI_CHALLENGE_SENT_INFO "They will receive a notification. Wait for them to accept or decline.\n"
#define CLIENT_UI_CHALLENGE_ERROR "Error: %s\n"

#define CLIENT_UI_NO_CHALLENGES "\nNo pending challenges\n"
#define CLIENT_UI_CHALLENGES_HEADER "\nPending challenges (%d):\n"
#define CLIENT_UI_CHALLENGES_SEPARATOR "═══════════════════════════════════════════════════\n"
#define CLIENT_UI_CHALLENGE_ITEM "  %d. %s wants to play!\n"
#define CLIENT_UI_CHALLENGES_FOOTER "═══════════════════════════════════════════════════\n"
#define CLIENT_UI_CHALLENGES_OPTIONS "\nChoose an option:\n"
#define CLIENT_UI_CHALLENGES_ACCEPT "  [number] Accept challenge\n"
#define CLIENT_UI_CHALLENGES_DECLINE "  d[number] Decline challenge\n"
#define CLIENT_UI_CHALLENGES_CANCEL "  0 Cancel\n"
#define CLIENT_UI_CHALLENGES_PROMPT "Your choice: "

#define CLIENT_UI_CHALLENGE_ACCEPTED "Challenge from %s accepted! Game will start shortly...\n"
#define CLIENT_UI_CHALLENGE_DECLINED "Challenge from %s declined\n"

#define CLIENT_UI_BIO_PROMPT_HEADER "\nSetting your bio (max 10 lines, 255 chars each)\n"
#define CLIENT_UI_BIO_PROMPT_INSTRUCTIONS "Enter your bio lines. Enter an empty line to finish:\n"
#define CLIENT_UI_BIO_PROMPT_LINE "Line %d: "
#define CLIENT_UI_BIO_UPDATED "Bio updated successfully (%d lines)\n"

#define CLIENT_UI_BIO_DISPLAY_HEADER "\nBio for %s:\n"
#define CLIENT_UI_BIO_DISPLAY_SEPARATOR "─────────────────────────────\n"
#define CLIENT_UI_BIO_DISPLAY_EMPTY "  (No bio set)\n"
#define CLIENT_UI_BIO_DISPLAY_LINE "  %s\n"
#define CLIENT_UI_BIO_DISPLAY_FOOTER "─────────────────────────────\n"
#define CLIENT_UI_BIO_DISPLAY_ERROR "%s\n"

#define CLIENT_UI_STATS_HEADER "\nStatistics for %s:\n"
#define CLIENT_UI_STATS_SEPARATOR "─────────────────────────────\n"
#define CLIENT_UI_STATS_GAMES_PLAYED "  Games played: %d\n"
#define CLIENT_UI_STATS_GAMES_WON "  Games won:    %d\n"
#define CLIENT_UI_STATS_GAMES_LOST "  Games lost:   %d\n"
#define CLIENT_UI_STATS_TOTAL_SCORE "  Total score:  %d\n"
#define CLIENT_UI_STATS_WIN_RATE "  Win rate:     %.1f%%\n"
#define CLIENT_UI_STATS_FOOTER "─────────────────────────────\n"
#define CLIENT_UI_STATS_DISPLAY_ERROR "%s\n"

#define CLIENT_UI_CHAT_MODE_HEADER "\nInteractive Chat Mode\n"
#define CLIENT_UI_CHAT_MODE_INSTRUCTIONS "Select recipient: 'all' for global chat or enter a player name for private chat\n"
#define CLIENT_UI_CHAT_MODE_RECIPIENT "Recipient: "
#define CLIENT_UI_CHAT_MODE_GLOBAL "Global chat mode selected. Type your messages below.\n"
#define CLIENT_UI_CHAT_MODE_PRIVATE "Private chat mode selected. Sending messages to %s.\n"
#define CLIENT_UI_CHAT_ERROR "Error: %s\n"

#define CLIENT_UI_NOTIFICATION_HEADER "\n\n=== NOTIFICATIONS ===\n"
#define CLIENT_UI_NOTIFICATION_CHALLENGE "   CHALLENGE RECEIVED!\n"
#define CLIENT_UI_NOTIFICATION_MESSAGE "   %s\n"
#define CLIENT_UI_NOTIFICATION_CHALLENGE_HINT "   Use option 3 to accept or decline this challenge\n"
#define CLIENT_UI_NOTIFICATION_SEPARATOR "═══════════════════════════════════════════════════\n"
#define CLIENT_UI_NOTIFICATION_PROMPT "Your choice: "

#define CLIENT_UI_GAME_STARTED_HEADER "\n\n=== GAME ===\n"
#define CLIENT_UI_GAME_STARTED_TITLE "   GAME STARTED!\n"
#define CLIENT_UI_GAME_STARTED_ID "   Game ID: %s\n"
#define CLIENT_UI_GAME_STARTED_PLAYERS "   Players: %s vs %s\n"
#define CLIENT_UI_GAME_STARTED_YOUR_SIDE "   You are: %s\n"
#define CLIENT_UI_GAME_STARTED_HINT "   Use option 7 to enter play mode\n"
#define CLIENT_UI_GAME_STARTED_SEPARATOR "═══════════════════════════════════════════════════\n"
#define CLIENT_UI_GAME_STARTED_PROMPT "Your choice: "

#define CLIENT_UI_SPECTATOR_JOINED_HEADER "\n\n=== SPECTATOR ===\n"
#define CLIENT_UI_SPECTATOR_JOINED_TITLE "   SPECTATOR JOINED: %s\n"
#define CLIENT_UI_SPECTATOR_JOINED_ID "   Game ID: %s\n"
#define CLIENT_UI_SPECTATOR_JOINED_COUNT "   Total spectators: %d\n"
#define CLIENT_UI_SPECTATOR_JOINED_SEPARATOR "═══════════════════════════════════════════════════\n"
#define CLIENT_UI_SPECTATOR_JOINED_PROMPT "Your choice: "

#define CLIENT_UI_GAME_OVER_HEADER "\n\n=== GAME OVER ===\n"
#define CLIENT_UI_GAME_OVER_TITLE "   GAME OVER!\n"
#define CLIENT_UI_GAME_OVER_MESSAGE "   %s\n"
#define CLIENT_UI_GAME_OVER_SEPARATOR "═══════════════════════════════════════════════════\n"
#define CLIENT_UI_GAME_OVER_PROMPT "Your choice: "

#define CLIENT_UI_CHAT_MESSAGE_HEADER "\n\n=== CHAT ===\n"
#define CLIENT_UI_CHAT_MESSAGE_GLOBAL "   GLOBAL CHAT from %s:\n"
#define CLIENT_UI_CHAT_MESSAGE_PRIVATE "   PRIVATE MESSAGE from %s:\n"
#define CLIENT_UI_CHAT_MESSAGE_TEXT "   %s\n"
#define CLIENT_UI_CHAT_MESSAGE_SEPARATOR "═══════════════════════════════════════════════════\n"
#define CLIENT_UI_CHAT_MESSAGE_PROMPT "Your choice: "

#define CLIENT_UI_CONNECTION_LOST "\nConnection lost - server disconnected\n"
#define CLIENT_UI_NETWORK_ERROR "\nNetwork error: %s (attempt %d/%d)\n"
#define CLIENT_UI_NETWORK_ERROR_MAX "Too many consecutive errors - disconnecting\n"

#define CLIENT_UI_TURN_YOUR_TURN "\nYOUR TURN!\n"
#define CLIENT_UI_TURN_LEGAL_MOVES "   Legal moves: "
#define CLIENT_UI_TURN_MOVE_SEPARATOR "%d "
#define CLIENT_UI_TURN_NO_MOVES "(none)"
#define CLIENT_UI_TURN_LINE1 "\n"
#define CLIENT_UI_TURN_PROMPT "\nEnter pit number or 'm' for menu: "

#define CLIENT_UI_WAITING_OPPONENT "\nWaiting for opponent...\n"
#define CLIENT_UI_WAITING_HINT "   Type 'm' + Enter to return to main menu\n"
#define CLIENT_UI_WAITING_PROMPT "> "

#define CLIENT_UI_PLAY_ERROR "%s\n"

#define CLIENT_UI_BOARD_SIMPLE_LINE1 "\n"
#define CLIENT_UI_BOARD_SIMPLE_PLAYER_B "  [%2d][%2d][%2d][%2d][%2d][%2d]  <- Player B (Score: %d)\n"
#define CLIENT_UI_BOARD_SIMPLE_PLAYER_A "  [%2d][%2d][%2d][%2d][%2d][%2d]  <- Player A (Score: %d)\n"
#define CLIENT_UI_BOARD_SIMPLE_TURN "  Current turn: Player %c\n"
#define CLIENT_UI_BOARD_SIMPLE_LINE2 "\n"

#define CLIENT_UI_BOARD_DETAILED_LINE1 "\n"
#define CLIENT_UI_BOARD_DETAILED_LINE2 "═══════════════════════════════════════════════════════════\n"
#define CLIENT_UI_BOARD_DETAILED_LINE3 "                    PLATEAU AWALE                          \n"
#define CLIENT_UI_BOARD_DETAILED_LINE4 "═══════════════════════════════════════════════════════════\n"
#define CLIENT_UI_BOARD_DETAILED_PLAYER_B "Joueur B: %s (Score: %d)                    %s\n"
#define CLIENT_UI_BOARD_DETAILED_LINE5 "\n"
#define CLIENT_UI_BOARD_DETAILED_TOP_ROW "   ┌────┬────┬────┬────┬────┬────┐\n"
#define CLIENT_UI_BOARD_DETAILED_TOP_PITS "   │%2d  │%2d  │%2d  │%2d  │%2d  │%2d  │\n"
#define CLIENT_UI_BOARD_DETAILED_TOP_LABELS "   │ 11 │ 10 │ 9  │ 8  │ 7  │ 6  │\n"
#define CLIENT_UI_BOARD_DETAILED_MIDDLE "   ├────┼────┼────┼────┼────┼────┤\n"
#define CLIENT_UI_BOARD_DETAILED_BOTTOM_LABELS "   │ 0  │ 1  │ 2  │ 3  │ 4  │ 5  │\n"
#define CLIENT_UI_BOARD_DETAILED_BOTTOM_PITS "   │%2d  │%2d  │%2d  │%2d  │%2d  │%2d  │\n"
#define CLIENT_UI_BOARD_DETAILED_BOTTOM_ROW "   └────┴────┴────┴────┴────┘\n"
#define CLIENT_UI_BOARD_DETAILED_LINE6 "\n"
#define CLIENT_UI_BOARD_DETAILED_PLAYER_A "%s Joueur A: %s (Score: %d)\n"
#define CLIENT_UI_BOARD_DETAILED_LINE7 "═══════════════════════════════════════════════════════════\n"
#define CLIENT_UI_BOARD_DETAILED_GAME_OVER "PARTIE TERMINEE - "
#define CLIENT_UI_BOARD_DETAILED_WINNER_A "%s gagne!\n"
#define CLIENT_UI_BOARD_DETAILED_WINNER_B "%s gagne!\n"
#define CLIENT_UI_BOARD_DETAILED_DRAW "Match nul!\n"
#define CLIENT_UI_BOARD_DETAILED_CURRENT_TURN "Tour du joueur: %s\n"
#define CLIENT_UI_BOARD_DETAILED_LINE8 "═══════════════════════════════════════════════════════════\n"
#define CLIENT_UI_BOARD_DETAILED_LINE9 "\n"

/* Friend management UI */
#define CLIENT_UI_FRIEND_MENU_HEADER "\nFriend Management\n"
#define CLIENT_UI_FRIEND_MENU_SEPARATOR "═════════════════════════════════════════════════════════\n"
#define CLIENT_UI_FRIEND_MENU_OPTION1 "  1. Add friend\n"
#define CLIENT_UI_FRIEND_MENU_OPTION2 "  2. Remove friend\n"
#define CLIENT_UI_FRIEND_MENU_OPTION3 "  3. List friends\n"
#define CLIENT_UI_FRIEND_MENU_OPTION4 "  4. Back to main menu\n"
#define CLIENT_UI_FRIEND_MENU_PROMPT "Your choice: "

#define CLIENT_UI_FRIEND_ADD_HEADER "\nAdd Friend\n"
#define CLIENT_UI_FRIEND_ADD_PROMPT "Enter player name to add as friend: "
#define CLIENT_UI_FRIEND_ADD_SUCCESS "Successfully added %s as friend\n"
#define CLIENT_UI_FRIEND_ADD_ERROR "Failed to add friend: %s\n"

#define CLIENT_UI_FRIEND_REMOVE_HEADER "\nRemove Friend\n"
#define CLIENT_UI_FRIEND_REMOVE_PROMPT "Enter friend name to remove: "
#define CLIENT_UI_FRIEND_REMOVE_SUCCESS "Successfully removed %s from friends\n"
#define CLIENT_UI_FRIEND_REMOVE_ERROR "Failed to remove friend: %s\n"

#define CLIENT_UI_FRIEND_LIST_HEADER "\nYour Friends (%d):\n"
#define CLIENT_UI_FRIEND_LIST_SEPARATOR "─────────────────────────────\n"
#define CLIENT_UI_FRIEND_LIST_ITEM "  %d. %s\n"
#define CLIENT_UI_FRIEND_LIST_EMPTY "  (No friends)\n"
#define CLIENT_UI_FRIEND_LIST_FOOTER "─────────────────────────────\n"

/* Saved games logging constants */
#define CLIENT_LOG_LIST_SAVED_GAMES_HEADER "\nList Saved Games for Review\n"
#define CLIENT_LOG_LIST_SAVED_GAMES_PROMPT "Enter player name to filter (or press Enter for all games): "
#define CLIENT_LOG_VIEW_SAVED_GAME_HEADER "\nView Saved Game\n"
#define CLIENT_LOG_VIEW_SAVED_GAME_PROMPT "Enter game ID: "

#endif /* CLIENT_LOGGING_STRINGS_H */